### ISSUE TITLE
Promises not work in ES6

### ISSUE THREAD

**Issue by ghost** [Azure/azure-documentdb-node-q#3]
Hi,

I'm writing my application in ES6.  Is your library using ES6 promises?

When I execute the initialize method, my code quits working on this line:

```
 return this.client.createCollectionAsync(database._self, collectionDefinition);
```

The problem is that "this" is undefined on this line.  ES6 promises always keep "this" sorted out so that "this" always works.

Does the promise library you're using have this capability?

Thank you!

Karl

``` javascript
import {inject} from 'aurelia-framework';
import {DocumentClient} from 'documentdb';
import DocumentDbPromises from 'documentdb-q-promises';
import {ApplicationState} from '../ApplicationState';

@inject(DocumentDbPromises, ApplicationState)
export class DocumentDbService {

    constructor(DocumentDbPromises, ApplicationState) {
        this.config = ApplicationState.configuration;
        let DocumentClient = DocumentDbPromises.DocumentClientWrapper;
        let endPoint = this.config.endPoint;
        let key = this.config.key;
        this.client = new DocumentClient(endPoint, {masterKey: key });
        this.database = null;
    }

    initialize() {
        let databaseId = this.config.databaseId;
        let toDoCollectionId = this.config.toDoCollectionId;
        var querySpec = {
            query: 'SELECT * FROM root r WHERE r.id=@id',
            parameters: [{
              name: '@id',
              value: databaseId
             }]
         };

         this.client.queryDatabases(querySpec).toArrayAsync()
             .then(function(promise){
                 if (promise.feed.length === 0) {
                     let databaseDefinition = { id: databaseId };
                     return this.client.createDatabaseAsync(databaseDefinition);
                 } else {
                     console.log("Database exists.")
                 }
             })
             .then(function(databaseResponse){
                 this.database = databaseResponse.resource;
                 let collectionDefinition = { id: toDoCollectionId };
                 return this.client.createCollectionAsync(database._self, collectionDefinition);
             })
             .then(function(collectionResponse) {
                 console.log("Database and collection has been created.")
             })
             .fail(function(error) {
                 console.log("An error occured", error);
                 return undefined;
             });
    }
}
```

**Comment by ghost** [comment]
It's using the q promises framework. I do not believe this uses ES6, yet.

**Comment by ghost** [comment]
Thank you.  I'm guessing I'll need to write my own wrapper that uses ES6.  

I really like this package, works perfect for ES5.

Thank you for the info.

Karl

**Comment by ghost** [comment]
Hi Ryan,

I was successful in wrapping documented using ES6 promises.  I'm using Aurelia and Electron for my app and need to use ES6 or TypeScript.

Is Microsoft considering writing a wrapper for ES6 and TypeScript for documentdb?

Best,

Karl

**Comment by ghost** [comment]
Good to hear you were successful wrapping it for ES6. Have you considered packaging this and publishing it on npm?

**Comment by ghost** [comment]
We will look at full ES6 support in the future. 

We're also looking at providing TypeScript definitions too.

**Comment by ghost** [comment]
I would totally do it.  I've never done this before, making a package.  I guess I could give it a go.

**Comment by ghost** [comment]
Be happy to assist you if you need.

**Comment by ghost** [comment]
Ryan,

OK thank you. I'll get it code complete soon and get back to you.

Really do like DocumentDb.  Much easier than the other offerings.

Best,

Karl

**Comment by ghost** [comment]
Thanks Karl. If your code is an extension to our q wrapper then we'd be happy to accept a PR to this module instead of a whole new one. Your call. 

But yes, ultimately we will have full ES6 support. 

And TypeScript.

**Comment by kdawg1406** [comment]
Ryan,

Right after my last post, I discovered that DocumentDB will be too expensive for users of my app.  It's a small app with very low disk space and bandwidth requirements.

I fully understand Microsofts offering and their expenses for keeping a DocumentDB online, even if its only used for less than an hour a day.

If you see ScottGu, please say hello and greetings from Karl Shifflett.

Best to you,

Karl
