### ISSUE TITLE
Avoid * in dependencies?

### ISSUE THREAD

**Issue by JanneSalo** [Azure/azure-documentdb-node-q#5]
The recent version (v1.5.0) of `documentdb` library breaks on Linux. Badly. (See https://github.com/Azure/azure-documentdb-node/issues/90). This also causes `documentdb-q-promises` to break just as badly. No worries, I thought, I'll just revert back to v1.4.0... nope, the broken version `documendb` module still gets installed because there's `"documentdb": "*"` in `package.json`'s dependencies. Since it clearly seems that broken releases for dependencies can break this module also, I'd urge you to consider explicitly specifying working versions of dependencies in `package.json`.

**Comment by JanneSalo** [comment]
I see this issue was conveniently closed right when `documentdb` 1.5.4 was released... with a fatal bug (https://github.com/Azure/azure-documentdb-node/issues/102) which AGAIN breaks also `documentdb-q-promises`.

Please, please, please reconsider my suggestion. For example, whenever a new version of `documentdb` is released, release also `documentdb-q-promises` with the same version number, with equal (and exact!) version of `documentdb` as requirement. This way, it's always possible for users to revert back to a working version if something goes south. You could do it even now, just create releases 1.5.1, 1.5.2, 1.5.3 and 1.5.4 to "catch up" with `documentdb`.

**Comment by ryancrawcour** [comment]
How does it break with 1.5.4? What is the error, ship we can fix it and release a new version of q?

**Comment by ryancrawcour** [comment]
Fair enough. Will release a version of documentdb-q-promises targeting a specific version.

**Comment by ghost** [comment]
We have taken a look in to this and believe that the way our packages dependency for this q wrapper is configured is correct.

The \* says when installing the q wrapper, check for ANY existing version of the core documentdb client installed. 
If there is none, THEN download and install the latest. 
If there is any version of documentdb already installed, then do nothing. 

^1.5.0 says when installing the q wrapper if AT LEAST 1.5.0 of documentdb is not installed THEN pull down the latest version, but if you are already on 1.5.0 or later then do nothing. 

So, to avoid using the latest core SDK each time, 
add the following to your application's packages.json

{
  "name": "NodeTest",
  "version": "0.0.0",
  "description": "NodeTest",
  "main": "app.js",
  "dependencies": {
    "documentdb": "^1.5.0",
    "documentdb-q-promises": "^1.5.0"
  }
}

If you want to set to a specific version, then remove the ^
  "dependencies": {
    "documentdb": "1.5.2",
    "documentdb-q-promises": "1.5.0"
  }

Now your project will always only want to use 1.5.0 of documentdb-q-promises and 1.5.2 of documentdb even if we release newer versions

**Comment by JanneSalo** [comment]
This is decent advice. I can live with this, thanks.
